In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df

,id,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,1,A,B,A,B,A,A,A,A,B,...,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843,2213.18
1,2,A,B,A,A,A,A,A,A,B,...,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,1283.60
2,5,A,B,A,A,B,A,A,A,B,...,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,3005.09
3,10,B,B,A,B,A,A,A,A,B,...,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,939.85
4,11,A,B,A,B,A,A,A,A,B,...,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,2763.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188313,587620,A,B,A,A,A,A,A,A,B,...,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216,1198.62
188314,587624,A,A,A,A,A,B,A,A,A,...,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872,1108.34
188315,587630,A,B,A,A,A,A,A,B,B,...,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888,5762.64
188316,587632,A,B,A,A,A,A,A,A,B,...,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707,1562.87
188317,587633,B,A,A,B,A,A,A,A,A,...,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460,4751.72

In [4]:
df = df.drop("id",axis=1)

In [5]:
df

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,A,B,A,B,A,A,A,A,B,A,...,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843,2213.18
1,A,B,A,A,A,A,A,A,B,B,...,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,1283.60
2,A,B,A,A,B,A,A,A,B,B,...,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,3005.09
3,B,B,A,B,A,A,A,A,B,A,...,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,939.85
4,A,B,A,B,A,A,A,A,B,B,...,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,2763.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188313,A,B,A,A,A,A,A,A,B,A,...,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216,1198.62
188314,A,A,A,A,A,B,A,A,A,A,...,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872,1108.34
188315,A,B,A,A,A,A,A,B,B,A,...,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888,5762.64
188316,A,B,A,A,A,A,A,A,B,B,...,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707,1562.87
188317,B,A,A,B,A,A,A,A,A,A,...,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460,4751.72

# Explatory data analysis

In [6]:
for column in df.columns:
    # Show only categorical variables unique values
    if str(df[column].dtype.name) == 'object':
        print("col:",column,"unique values:",df[column].unique())

col: cat1 unique values: ['A' 'B']
col: cat2 unique values: ['B' 'A']
col: cat3 unique values: ['A' 'B']
col: cat4 unique values: ['B' 'A']
col: cat5 unique values: ['A' 'B']
col: cat6 unique values: ['A' 'B']
col: cat7 unique values: ['A' 'B']
col: cat8 unique values: ['A' 'B']
col: cat9 unique values: ['B' 'A']
col: cat10 unique values: ['A' 'B']
col: cat11 unique values: ['B' 'A']
col: cat12 unique values: ['A' 'B']
col: cat13 unique values: ['A' 'B']
col: cat14 unique values: ['A' 'B']
col: cat15 unique values: ['A' 'B']
col: cat16 unique values: ['A' 'B']
col: cat17 unique values: ['A' 'B']
col: cat18 unique values: ['A' 'B']
col: cat19 unique values: ['A' 'B']
col: cat20 unique values: ['A' 'B']
col: cat21 unique values: ['A' 'B']
col: cat22 unique values: ['A' 'B']
col: cat23 unique values: ['B' 'A']
col: cat24 unique values: ['A' 'B']
col: cat25 unique values: ['A' 'B']
col: cat26 unique values: ['A' 'B']
col: cat27 unique values: ['A' 'B']
col: cat28 unique values: ['A' 'B']
col: cat29 unique values: ['A' 'B']
col: cat30 unique values: ['A' 'B']
col: cat31 unique values: ['A' 'B']
col: cat32 unique values: ['A' 'B']
col: cat33 unique values: ['A' 'B']
col: cat34 unique values: ['A' 'B']
col: cat35 unique values: ['A' 'B']
col: cat36 unique values: ['A' 'B']
col: cat37 unique values: ['A' 'B']
col: cat38 unique values: ['A' 'B']
col: cat39 unique values: ['A' 'B']
col: cat40 unique values: ['A' 'B']
col: cat41 unique values: ['A' 'B']
col: cat42 unique values: ['A' 'B']
col: cat43 unique values: ['A' 'B']
col: cat44 unique values: ['A' 'B']
col: cat45 unique values: ['A' 'B']
col: cat46 unique values: ['A' 'B']
col: cat47 unique values: ['A' 'B']
col: cat48 unique values: ['A' 'B']
col: cat49 unique values: ['A' 'B']
col: cat50 unique values: ['A' 'B']
col: cat51 unique values: ['A' 'B']
col: cat52 unique values: ['A' 'B']
col: cat53 unique values: ['A' 'B']
col: cat54 unique values: ['A' 'B']
col: cat55 unique values: ['A' 'B']
col: cat56 unique values: ['A' 'B']
col: cat57 unique values: ['A' 'B']
col: cat58 unique values: ['A' 'B']
col: cat59 unique values: ['A' 'B']
col: cat60 unique values: ['A' 'B']
col: cat61 unique values: ['A' 'B']
col: cat62 unique values: ['A' 'B']
col: cat63 unique values: ['A' 'B']
col: cat64 unique values: ['A' 'B']
col: cat65 unique values: ['A' 'B']
col: cat66 unique values: ['A' 'B']
col: cat67 unique values: ['A' 'B']
col: cat68 unique values: ['A' 'B']
col: cat69 unique values: ['A' 'B']
col: cat70 unique values: ['A' 'B']
col: cat71 unique values: ['A' 'B']
col: cat72 unique values: ['A' 'B']
col: cat73 unique values: ['A' 'B' 'C']
col: cat74 unique values: ['A' 'B' 'C']
col: cat75 unique values: ['B' 'A' 'C']
col: cat76 unique values: ['A' 'C' 'B']
col: cat77 unique values: ['D' 'C' 'B' 'A']
col: cat78 unique values: ['B' 'A' 'C' 'D']
col: cat79 unique values: ['B' 'D' 'A' 'C']
col: cat80 unique values: ['D' 'B' 'A' 'C']
col: cat81 unique values: ['D' 'B' 'A' 'C']
col: cat82 unique values: ['B' 'A' 'D' 'C']
col: cat83 unique values: ['D' 'B' 'A' 'C']
col: cat84 unique values: ['C' 'A' 'D' 'B']
col: cat85 unique values: ['B' 'A' 'C' 'D']
col: cat86 unique values: ['D' 'B' 'C' 'A']
col: cat87 unique values: ['B' 'C' 'D' 'A']
col: cat88 unique values: ['A' 'D' 'E' 'B']
col: cat89 unique values: ['A' 'B' 'C' 'E' 'D' 'H' 'I' 'G']
col: cat90 unique values: ['A' 'B' 'C' 'D' 'F' 'E' 'G']
col: cat91 unique values: ['A' 'B' 'G' 'C' 'D' 'E' 'F' 'H']
col: cat92 unique values: ['A' 'H' 'B' 'C' 'D' 'I' 'F']
col: cat93 unique values: ['D' 'C' 'A' 'B' 'E']
col: cat94 unique values: ['B' 'D' 'C' 'A' 'F' 'E' 'G']
col: cat95 unique values: ['C' 'D' 'E' 'A' 'B']
col: cat96 unique values: ['E' 'D' 'G' 'B' 'F' 'A' 'I' 'C']
col: cat97 unique values: ['A' 'E' 'C' 'G' 'D' 'F' 'B']
col: cat98 unique values: ['C' 'D' 'A' 'E' 'B']
col: cat99 unique values: ['T' 'D' 'P' 'S' 'R' 'K' 'E' 'F' 'N' 'J' 'C' 'M' 'H' 'G' 'I' 'O']
col: cat100 unique values: ['B' 'L' 'I' 'F' 'J' 'H' 'C' 'M' 'A' 'G' 'O' 'N' 'K' 'D' 'E']
col: cat101 unique values: ['G' 'F' 'O' 'D' 'J' 'A' 'C' 'Q' 'M' 'I' 'L' 'R' 'S' 'E' 'N' 'H' 'B' 'U'
 'K']
col: cat102 unique values: ['A' 'C' 'B' 'D' 'G' 'E' 'F' 'H' 'J']
col: cat103 unique values: ['A' 'B' 'C' 'F' 'E' 'D' 'G' 'H' 'I' 'L' 'K' 'J' 'N']
col: cat104 unique values: ['I' 'E' 'D' 'K' 'H' 'F' 'G' 'P' 'C' 'J' 'L' 'M' 'N' 'O' 'B' 'A' 'Q']
col: cat105 unique values: ['E' 'F' 'H' 'G' 'I' 'D' 'J' 'K' 'M' 'C' 'A' 'L' 'N' 'P' 'T' 'Q' 'R' 'O'
 'B' 'S']
col: cat106 unique values: ['G' 'I' 'H' 'K' 'F' 'J' 'E' 'L' 'M' 'D' 'A' 'C' 'N' 'O' 'R' 'B' 'P']
col: cat107 unique values: ['J' 'K' 'F' 'G' 'I' 'M' 'H' 'L' 'E' 'D' 'O' 'C' 'N' 'A' 'Q' 'P' 'U' 'B'
 'R' 'S']
col: cat108 unique values: ['G' 'K' 'A' 'B' 'D' 'I' 'F' 'H' 'E' 'C' 'J']
col: cat109 unique values: ['BU' 'BI' 'AB' 'H' 'K' 'CD' 'BQ' 'M' 'G' 'BL' 'L' 'AL' 'N' 'CL' 'R' 'F'
 'BJ' 'AR' 'AT' 'S' 'AS' 'BO' 'X' 'D' 'BM' 'I' 'BH' 'CI' 'CF' 'C' 'AM' 'U'
 'BE' 'BR' 'CJ' 'AE' 'A' 'Q' 'AW' 'T' 'AJ' 'AH' 'BA' 'BV' 'CC' 'CA' 'BG'
 'BB' 'O' 'BD' 'AV' 'AX' 'AQ' 'AA' 'AI' 'AU' 'BX' 'AP' 'CK' 'Y' 'CH' 'BS'
 'AN' 'AO' 'BC' 'CE' 'E' 'BY' 'CB' 'BT' 'P' 'BK' 'AF' 'B' 'BF' 'CG' 'V'
 'ZZ' 'AY' 'BP' 'BN' 'J' 'AG' 'AK']
col: cat110 unique values: ['BC' 'CQ' 'DK' 'CS' 'C' 'EB' 'DW' 'AM' 'AI' 'EG' 'CL' 'BS' 'BT' 'CO' 'CM'
 'EL' 'AY' 'W' 'EE' 'AC' 'DX' 'CI' 'DT' 'A' 'V' 'DM' 'EF' 'DL' 'DA' 'BP'
 'DH' 'CF' 'N' 'T' 'CR' 'X' 'CH' 'EM' 'DC' 'AX' 'BG' 'CJ' 'EA' 'AD' 'U'
 'AK' 'BX' 'AW' 'G' 'BA' 'L' 'AP' 'CG' 'R' 'DU' 'I' 'AR' 'O' 'DF' 'AT' 'E'
 'AB' 'AU' 'DI' 'CN' 'CP' 'AL' 'ED' 'DJ' 'AO' 'CY' 'BE' 'BJ' 'D' 'AA' 'CK'
 'CV' 'BK' 'BB' 'AE' 'BO' 'P' 'DO' 'CT' 'AJ' 'BR' 'Y' 'DR' 'BQ' 'BL' 'B'
 'BW' 'H' 'DP' 'DG' 'AG' 'BN' 'J' 'CW' 'DV' 'Q' 'DY' 'EI' 'AV' 'DQ' 'BU'
 'K' 'BF' 'BD' 'DS' 'DE' 'BM' 'BY' 'CD' 'BI' 'DD' 'DB' 'AH' 'CC' 'DN' 'CU'
 'BV' 'CX' 'AN' 'EK' 'EJ' 'AS' 'AF' 'CB' 'EH' 'S']
col: cat111 unique values: ['C' 'A' 'G' 'E' 'I' 'M' 'W' 'S' 'K' 'O' 'Q' 'U' 'F' 'B' 'Y' 'D']
col: cat112 unique values: ['AS' 'AV' 'C' 'N' 'Y' 'J' 'AH' 'K' 'U' 'E' 'AK' 'AI' 'AE' 'A' 'L' 'F'
 'AP' 'AD' 'AF' 'AL' 'AN' 'S' 'AW' 'I' 'AR' 'AX' 'AU' 'AQ' 'O' 'AO' 'R'
 'H' 'G' 'AC' 'AT' 'AG' 'X' 'AA' 'Q' 'AY' 'D' 'BA' 'P' 'B' 'AM' 'M' 'T'
 'W' 'V' 'AB' 'AJ']
col: cat113 unique values: ['S' 'BM' 'AF' 'AE' 'Y' 'AX' 'H' 'K' 'L' 'A' 'J' 'AK' 'N' 'M' 'AJ' 'AT'
 'F' 'BC' 'AY' 'AD' 'BG' 'BO' 'AS' 'BD' 'AN' 'I' 'BF' 'BK' 'AW' 'AG' 'BJ'
 'AO' 'Q' 'AM' 'X' 'AU' 'BN' 'BH' 'AI' 'C' 'AV' 'AQ' 'AH' 'G' 'E' 'BA'
 'AL' 'BI' 'U' 'AB' 'V' 'O' 'BB' 'AP' 'B' 'BL' 'BE' 'T' 'P' 'AC' 'AR']
col: cat114 unique values: ['A' 'J' 'E' 'C' 'F' 'L' 'N' 'I' 'R' 'U' 'O' 'B' 'Q' 'V' 'D' 'X' 'W' 'S'
 'G']
col: cat115 unique values: ['O' 'I' 'K' 'P' 'Q' 'L' 'J' 'R' 'N' 'M' 'H' 'G' 'F' 'A' 'S' 'W' 'T' 'C'
 'E' 'D' 'B' 'X' 'U']
col: cat116 unique values: ['LB' 'DP' 'GK' 'DJ' 'CK' 'LO' 'IE' 'LY' 'GS' 'HK' 'DC' 'MP' 'DS' 'LE'
 'HQ' 'HJ' 'GC' 'BY' 'HX' 'HL' 'HG' 'MD' 'LF' 'LM' 'CB' 'CS' 'KQ' 'HN'
 'LQ' 'KW' 'IT' 'LN' 'CW' 'LC' 'GX' 'GE' 'CP' 'HB' 'GI' 'GM' 'CR' 'JR'
 'HA' 'EE' 'BA' 'LJ' 'IH' 'HV' 'GU' 'HM' 'CY' 'IC' 'KD' 'KI' 'DN' 'MG'
 'LL' 'KN' 'LH' 'DF' 'EY' 'LW' 'KA' 'EK' 'DK' 'EO' 'CG' 'K' 'HC' 'DI' 'FB'
 'IG' 'FR' 'CI' 'EC' 'KR' 'HI' 'IU' 'MC' 'BP' 'JW' 'FH' 'IF' 'E' 'DA' 'KL'
 'LX' 'IL' 'KB' 'IQ' 'EL' 'JX' 'H' 'GN' 'CD' 'DH' 'AC' 'FD' 'ME' 'KC' 'FT'
 'CT' 'DM' 'GL' 'ES' 'JL' 'BX' 'II' 'HP' 'ED' 'CU' 'EN' 'FG' 'MJ' 'KE'
 'CF' 'EB' 'DD' 'EI' 'FX' 'EA' 'BO' 'KP' 'EP' 'FC' 'GB' 'JU' 'LV' 'CO'
 'EF' 'BD' 'HW' 'LI' 'GT' 'HH' 'KJ' 'CN' 'B' 'FE' 'GA' 'FW' 'IY' 'MO' 'JG'
 'ID' 'DX' 'FA' 'LA' 'HR' 'GJ' 'GO' 'KT' 'GW' 'U' 'MI' 'GP' 'F' 'DU' 'KM'
 'BV' 'DT' 'IM' 'LD' 'GR' 'HD' 'BS' 'AJ' 'KX' 'LR' 'ML' 'KU' 'CE' 'IA'
 'DE' 'R' 'AO' 'MU' 'AK' 'CX' 'HY' 'EH' 'MA' 'GH' 'LK' 'DL' 'AX' 'IN' 'BI'
 'JM' 'JF' 'KK' 'DR' 'LT' 'GF' 'AW' 'KY' 'CA' 'MK' 'DV' 'EG' 'DW' 'MN' 'V'
 'CM' 'GY' 'AF' 'JC' 'MR' 'JE' 'IP' 'KV' 'KH' 'BW' 'MQ' 'D' 'HF' 'CV' 'BL'
 'FL' 'GV' 'CQ' 'BM' 'JB' 'J' 'FU' 'AG' 'EJ' 'CH' 'MW' 'X' 'DG' 'AV' 'EW'
 'O' 'DO' 'BK' 'FS' 'T' 'CL' 'Y' 'JQ' 'I' 'AL' 'JJ' 'HT' 'FF' 'JA' 'GD'
 'FV' 'BQ' 'M' 'S' 'EU' 'P' 'FJ' 'AR' 'LG' 'IR' 'GQ' 'MM' 'AY' 'MF' 'GG'
 'KG' 'JD' 'L' 'KS' 'AH' 'JV' 'EV' 'CC' 'AB' 'FK' 'JY' 'G' 'W' 'BC' 'AM'
 'KF' 'LU' 'IK' 'BU' 'AT' 'JP' 'Q' 'IJ' 'JO' 'JH' 'AS' 'JN' 'BF' 'AD' 'FP'
 'MV' 'AA' 'CJ' 'DY' 'IB' 'AN' 'EQ' 'JT' 'BG' 'AP' 'MB' 'JK' 'FI' 'MS'
 'HE' 'C' 'IV' 'IO' 'BT' 'DQ' 'FM' 'HO' 'MH' 'MT' 'FO' 'JI' 'FQ' 'AU' 'FN'
 'BB' 'HU' 'IX' 'AE']

In [7]:
# Exploring for null values
Flag = False
for c in df.columns:
    # Show only categorical variables unique values
    count = df[column].isnull().sum()
    if count > 0:
        print("col:",column, "has",count,"null values")
        Flag = True
if not Flag:
    print("No null values have been found")

No null values have been found

## Only numerical values could be digested by the machine learning algorithms so we have to encode the characters to numbers assigning them from 0 to their count.
### A = 0, B = 1, ... Z = 25

In [8]:
# iterate through each column
for column in df.columns:
    # check if column contains numerical data
    if df[column].dtype == 'float64' or df[column].dtype == 'int64':
        continue
    # create a dictionary to map unique values to their count
    value_counts = df[column].value_counts().to_dict()
    # create a new column with encoded values
    encoded_column = df[column].apply(lambda x: list(value_counts.keys()).index(x))
    # replace the original column with the encoded column
    df[column] = encoded_column

In [9]:
df

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,0,1,0,1,0,0,0,0,1,0,...,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843,2213.18
1,0,1,0,0,0,0,0,0,1,1,...,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496,1283.60
2,0,1,0,0,1,0,0,0,1,1,...,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425,3005.09
3,1,1,0,1,0,0,0,0,1,0,...,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642,939.85
4,0,1,0,1,0,0,0,0,1,1,...,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606,2763.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188313,0,1,0,0,0,0,0,0,1,0,...,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216,1198.62
188314,0,0,0,0,0,1,0,0,0,0,...,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872,1108.34
188315,0,1,0,0,0,0,0,1,1,0,...,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888,5762.64
188316,0,1,0,0,0,0,0,0,1,1,...,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707,1562.87
188317,1,0,0,1,0,0,0,0,0,0,...,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460,4751.72

In [10]:
X = df.drop("loss",axis=1)
y = df['loss']

In [11]:
X

,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14
0,0,1,0,1,0,0,0,0,1,0,...,0.310061,0.718367,0.335060,0.30260,0.67135,0.83510,0.569745,0.594646,0.822493,0.714843
1,0,1,0,0,0,0,0,0,1,1,...,0.885834,0.438917,0.436585,0.60087,0.35127,0.43919,0.338312,0.366307,0.611431,0.304496
2,0,1,0,0,1,0,0,0,1,1,...,0.397069,0.289648,0.315545,0.27320,0.26076,0.32446,0.381398,0.373424,0.195709,0.774425
3,1,1,0,1,0,0,0,0,1,0,...,0.422268,0.440945,0.391128,0.31796,0.32128,0.44467,0.327915,0.321570,0.605077,0.602642
4,0,1,0,1,0,0,0,0,1,1,...,0.704268,0.178193,0.247408,0.24564,0.22089,0.21230,0.204687,0.202213,0.246011,0.432606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188313,0,1,0,0,0,0,0,0,1,0,...,0.939556,0.242437,0.289949,0.24564,0.30859,0.32935,0.223038,0.220003,0.333292,0.208216
188314,0,0,0,0,0,1,0,0,0,0,...,0.704268,0.334270,0.382000,0.63475,0.40455,0.47779,0.307628,0.301921,0.318646,0.305872
188315,0,1,0,0,0,0,0,1,1,0,...,0.482436,0.345883,0.370534,0.24564,0.45808,0.47779,0.445614,0.443374,0.339244,0.503888
188316,0,1,0,0,0,0,0,0,1,1,...,0.340543,0.704364,0.562866,0.34987,0.44767,0.53881,0.863052,0.852865,0.654753,0.721707
188317,1,0,0,1,0,0,0,0,0,0,...,0.281143,0.844563,0.533048,0.97123,0.93383,0.83814,0.932195,0.946432,0.810511,0.721460

In [12]:
y

0         2213.18
1         1283.60
2         3005.09
3          939.85
4         2763.85
           ...
188313    1198.62
188314    1108.34
188315    5762.64
188316    1562.87
188317    4751.72
Name: loss, Length: 188318, dtype: float64

In [13]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error

from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import HistGradientBoostingRegressor

In [14]:
def predict_mae(c,X,y,p=False):
    print(c)
    y_preds = c.predict(X)
    if p:
        print(mean_absolute_error(y,y_preds))
    return mean_absolute_error(y,y_preds)

In [15]:
len(X)

188318

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Training algorithms individually and finding out their Mean Absolute Error (the lower the better)

In [17]:
MLP_R = MLPRegressor()
MLP_R.fit(X_train,y_train)
predict_mae(MLP_R,X_test,y_test)

MLPRegressor()

C:\Users\SSD BILL\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

1255.1616633895126

In [18]:
KNN_R = KNeighborsRegressor()
KNN_R.fit(X_train,y_train)
predict_mae(KNN_R,X_test,y_test)

KNeighborsRegressor()

1613.1629477060321

In [19]:
Bagging_R = BaggingRegressor()
Bagging_R.fit(X_train,y_train)
predict_mae(Bagging_R,X_test,y_test)

BaggingRegressor()

1314.1571533559897

In [20]:
HGB_R = HistGradientBoostingRegressor()
HGB_R.fit(X_train,y_train)
predict_mae(HGB_R,X_test,y_test)

HistGradientBoostingRegressor()

1198.5383692996306

# Unfinished part using GridSearch for parameter tuning

In [18]:
import mustafapy

In [19]:
from mustafapy import mustafa
m = mustafa(atype='reg',precision=2,hyperstep=5,maxattrs=2,selection=['KNeighborsRegressor','BaggingRegressor', 'HistGradientBoostingRegressor'])
hypers_dictionary = m.hypers()
m.hypers()

['KNeighborsRegressor']

Feel free to share your training results to improve {mustafa} by setting (stats=True) in the constructor :)

{sklearn.neighbors._regression.KNeighborsRegressor: {'n_neighbors': [5],
  'weights': ['uniform', 'distance'],
  'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}}

In [20]:
regressors = [KNeighborsRegressor(),BaggingRegressor(),HistGradientBoostingRegressor()]
for r in regressors:
    print(hypers_dictionary[r.__class__])

{'n_neighbors': [5], 'weights': ['uniform', 'distance'], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

In [ ]:
for reg in regressors:
    parameters = hypers_dictionary[reg.__class__]

    reg_GS = RandomizedSearchCV(reg,
                          parameters,
                          cv=None,
                          scoring='neg_mean_absolute_error',
                           n_jobs=-1,
                            n_iter=10,
                            verbose=3
                          )

    reg_GS.fit(X, y)
    predict_mae(reg_GS.best_estimator_,X_test,y_test,p=True)